package mods.fossil.gens.structure.shipwreck;

import net.minecraft.block.Block;

public class ShipWreck3
{
    /** Some predefined values for custom hooks that I use in the demo structure */
    public static final int CUSTOM_CHEST = 4097, CUSTOM_DISPENSER = 4098, ITEM_FRAME = 4099, PAINTING = 4100,
                            SPAWN_VILLAGER = 4101, CUSTOM_SKULL = 4102, CUSTOM_SIGNWALL = 4103, CUSTOM_SIGNPOST = 4104, RANDOM_HOLE = 4105;

    /** Start of specific chests; I'll use negative values so as not to conflict with item types and such */
    public static final int CUSTOM_CHEST_1 = -1;

    /** Custom signs */
    public static final int CUSTOM_SIGN_1 = 1;

    public static final int[][][][] blockArrayShipWreck3 =
    {
        //This is where all the x, y, z values go (i, j, k). They are broke down by
        //layer. This is how the array works building from x to z and by layer y,
        //then they are finished by removing all the world.setBlock and
        //x, y, z coordinates leaving something like this {Block.stone.blockID},
        {
            //y = 12
            {
                //x = 0
                {},
                {},
                {},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 1
                {},
                {},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 2
                {},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {Block.stairsWoodOak.blockID, 3},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 3
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {Block.stairsWoodOak.blockID, 3},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 4
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
            },
            {
                //x = 5
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {Block.ladder.blockID, 2},
                {RANDOM_HOLE, Block.wood.blockID},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, Block.wood.blockID},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
            },
            {
                //x = 6
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, Block.wood.blockID},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, Block.wood.blockID},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
            },
            {
                //x = 7
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
            },
            {
                //x = 8
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {Block.stairsWoodOak.blockID, 3},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
            },
            {
                //x = 9
                {},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {Block.stairsWoodOak.blockID, 3},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 10
                {},
                {},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 11
                {},
                {},
                {},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            }
        },
        {
            //y = 13
            {
                //x = 0
                {},
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 1
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 2
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 3
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 4
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 5
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {Block.ladder.blockID, 2},
                {RANDOM_HOLE, Block.wood.blockID},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, Block.wood.blockID},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 6
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, Block.wood.blockID},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {RANDOM_HOLE, Block.wood.blockID},
                {RANDOM_HOLE, Block.wood.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
                {ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
            },
            {
                //x = 7
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 8
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 9
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 10
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
            },
            {
                //x = 11
                {},
                {},
                {},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {RANDOM_HOLE, 0, Block.fence.blockID},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            }
        }
    };
}
