package mods.fossil.gens.structure.academy;

import java.util.Random;

import mods.fossil.Fossil;
import net.minecraft.block.Block;
import net.minecraft.world.World;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraft.world.biome.BiomeGenBeach;
import net.minecraft.world.biome.BiomeGenDesert;
import net.minecraft.world.biome.BiomeGenForest;
import net.minecraft.world.biome.BiomeGenHills;
import net.minecraft.world.biome.BiomeGenJungle;
import net.minecraft.world.biome.BiomeGenPlains;
import net.minecraft.world.biome.BiomeGenRiver;
import net.minecraft.world.biome.BiomeGenSnow;
import net.minecraft.world.biome.BiomeGenSwamp;
import net.minecraft.world.biome.BiomeGenTaiga;

public class Academy1
{


	public static final int[][][][] blockArrayAcademy =
	{//This is where all the x, y, z values go (i, j, k). They are broke down by
		//layer. This is how the array works building from x to z and by layer y,
		//then they are finished by removing all the world.setBlock and 
		//x, y, z coordinates leaving something like this {Block.stone.blockID},
		{//y = 0 LAYER1
			{//x = 0
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 1
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 2
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 3
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 4
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 5
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 6
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 7
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 8
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 9
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 10
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 11
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 12
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 13
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.torchRedstoneActive.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 14
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 15
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 16
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 17
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 18
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 19
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 20
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 21
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 22
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 23
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			}			
		},
		{//y = 0 LAYER1
			{//x = 0
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 1
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 2
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 3
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 4
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 5
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 6
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 7
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 8
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 9
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 10
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 11
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 12
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 13
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.torchRedstoneActive.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 14
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 15
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.glass.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneDoubleSlab.blockID, 3},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 16
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 17
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 18
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 19
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			},
			{//x = 20
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 21
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 22
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.grass.blockID},
			},
			{//x = 23
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
				{}, //{Block.grass.blockID},
			}			
		},
		{//y = 1 LAYER2
			{//x = 0
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 1
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.mushroomBrown.blockID},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.mushroomBrown.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{0}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 2
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.stoneBrick.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 3
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{},
				{}, //{Block.mushroomBrown.blockID},
				{Block.stoneBrick.blockID, 1},
				{0}, //{Block.mushroomBrown.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.CUSTOM_CHEST, 5, 1},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 5, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 4
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 5
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 2, AcademyUtil.RARE_LOOT_1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 6
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 2, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 7
				{},
				{}, //{Block.plantYellow.blockID},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.furnaceIdle.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 8
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 9
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.enchantmentTable.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{},
			},
			{//x = 10
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{}, //{Block.plantYellow.blockID},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{Block.pressurePlateStone.blockID},
				{Block.doorIron.blockID, 4},
				{},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 12
				{},
				{},
				{},
				{},
				{},
				{Block.doorIron.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{},
			},
			{//x = 13
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{},
			},
			{//x = 14
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.mushroomBrown.blockID},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 15
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.plantYellow.blockID},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 16
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{Block.blockGold.blockID},
				{Block.furnaceIdle.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 17
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 2, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.plantYellow.blockID},
				{},
			},
			{//x = 18
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 2, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{},
			},
			{//x = 19
				{},
				{}, //{Block.plantYellow.blockID},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 20
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.plantYellow.blockID},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.CUSTOM_CHEST, 4, 1},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 4, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 21
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 22
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.mushroomBrown.blockID},
				{}, //{Block.tallGrass.blockID, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{}, //{Block.tallGrass.blockID, 1},
			},
			{//x = 23
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{},
				{}, //{Block.plantYellow.blockID},
				{}, //{Block.plantYellow.blockID},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.plantYellow.blockID},
				{}, //{Block.plantYellow.blockID},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.tallGrass.blockID, 1},
				{},
				{}, //{Block.tallGrass.blockID, 1},
				{}, //{Block.plantYellow.blockID},
			}			
		},
		{//y = 4
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.CUSTOM_CHEST, 5, 1},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 5, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{},
				{},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.blockClay.blockID},
				{0},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 2, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 2, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE, 0, Block.stoneDoubleSlab.blockID},
				{Block.furnaceIdle.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{Block.doorIron.blockID, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 12
				{},
				{},
				{},
				{},
				{},
				{Block.doorIron.blockID, 9},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 13
				{},
				{},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 14
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 15
				{},
				{},
				{},
				{},
				{},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 16
				{},
				{},
				{},
				{},
				{},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 17
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 2, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 18
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 2, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 19
				{},
				{},
				{},
				{},
				{},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 20
				{},
				{},
				{},
				{},
				{},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.CUSTOM_CHEST, 4, AcademyUtil.RARE_LOOT_1},
				{0},
				{AcademyUtil.CUSTOM_CHEST, 4, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 21
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 22
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 23
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}}};
}