package mods.fossil.gens.structure.shipwreck;

import net.minecraft.block.Block;

public class ShipWreck1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST = 4097, CUSTOM_DISPENSER = 4098, ITEM_FRAME = 4099, PAINTING = 4100,
			SPAWN_VILLAGER = 4101, CUSTOM_SKULL = 4102, CUSTOM_SIGNWALL = 4103, CUSTOM_SIGNPOST = 4104, RANDOM_HOLE = 4105;

	/** Start of specific chests; I'll use negative values so as not to conflict with item types and such */
	public static final int CUSTOM_CHEST_1 = -1;

	/** Custom signs */
	public static final int CUSTOM_SIGN_1 = 1;

	public static final int[][][][] blockArrayShipWreck1 =
	{//This is where all the x, y, z values go (i, j, k). They are broke down by
		//layer. This is how the array works building from x to z and by layer y,
		//then they are finished by removing all the world.setBlock and 
		//x, y, z coordinates leaving something like this {Block.stone.blockID},
		{//y = 0
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 1
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 2
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 3
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{Block.doorWood.blockID, 1},
				{Block.pressurePlatePlanks.blockID},
				{Block.chest.blockID, 5},
				{Block.chest.blockID, 5},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{Block.furnaceIdle.blockID, 2},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{Block.furnaceIdle.blockID, 2},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{Block.chest.blockID, 4},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 4
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{Block.signWall.blockID, 2},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{Block.doorWood.blockID, 9},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.furnaceIdle.blockID, 2},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.furnaceIdle.blockID, 2},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.glass.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 5
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{RANDOM_HOLE, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{}
			}}};
}