package mods.fossil.gens.structure.academy;

import mods.fossil.Fossil;
import net.minecraft.block.Block;

public class Academy1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST = 4097, CUSTOM_DISPENSER = 4098, ITEM_FRAME = 4099, PAINTING = 4100,
			SPAWN_VILLAGER = 4101, CUSTOM_SKULL = 4102, CUSTOM_SIGNWALL = 4103, CUSTOM_SIGNPOST = 4104, RANDOM_HOLE = 4105;

	/** Start of specific chests; I'll use negative values so as not to conflict with item types and such */
	public static final int CUSTOM_CHEST_1 = -1;

	/** Custom signs */
	public static final int CUSTOM_SIGN_1 = 1;

	public static final int[][][][] blockArrayAcademy =
	{//This is where all the x, y, z values go (i, j, k). They are broke down by
		//layer. This is how the array works building from x to z and by layer y,
		//then they are finished by removing all the world.setBlock and 
		//x, y, z coordinates leaving something like this {Block.stone.blockID},
		/*
		{//y = 0
			{//x = 0
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 1
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 2
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 3
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 4
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 5
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 6
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 7
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 8
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 9
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 10
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 11
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 12
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 13
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 14
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 15
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 16
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 17
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 18
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 19
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 20
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 21
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 22
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 23
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			}			
		},
		{//y = 1
			{//x = 0
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 1
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 2
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 3
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 4
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 5
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 6
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 7
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 8
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 9
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 10
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 11
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.redstoneWire.blockID},
				{Block.redstoneWire.blockID},
				{Block.dirt.blockID},
				{Block.torchRedstoneActive.blockID, 3},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 12
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.torchRedstoneIdle.blockID, 2},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 13
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.redstoneWire.blockID, 14},
				{Block.redstoneWire.blockID, 15},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 14
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 15
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 16
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 17
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 18
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 19
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 20
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 21
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 22
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 23
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			}			
		},
		*/
		{//y = 2
			{//x = 0
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 1
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 2
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 3
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 4
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 5
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 6
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 7
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 8
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.glass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 9
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID},
				{Block.glass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.glass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 10
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 11
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 12
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 13
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.torchRedstoneActive.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 14
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.dirt.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID},
				{Block.glass.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.glass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 15
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.glass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 16
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 17
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 18
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 19
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 20
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 21
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 22
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0}, //{Block.grass.blockID},
			},
			{//x = 23
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
				{0}, //{Block.grass.blockID},
			}			
		},
		{//y = 3
			{//x = 0
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 1
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.mushroomBrown.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.mushroomBrown.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 2
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 3
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.mushroomBrown.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.mushroomBrown.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.chest.blockID, 5},
				{0},
				{Block.chest.blockID, 5},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 4
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 5
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 6
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 7
				{0},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.furnaceIdle.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 8
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 9
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.enchantmentTable.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{Block.plantYellow.blockID},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorIron.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.doorIron.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
			},
			{//x = 13
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
			},
			{//x = 14
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.mushroomBrown.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 15
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 16
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{Block.blockGold.blockID},
				{Block.furnaceIdle.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 17
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.plantYellow.blockID},
				{0},
			},
			{//x = 18
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
			},
			{//x = 19
				{0},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 20
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantRed.blockID},
				{Block.plantYellow.blockID},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.chest.blockID, 4},
				{0},
				{Block.chest.blockID, 4},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 21
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 22
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.mushroomBrown.blockID},
				{Block.tallGrass.blockID, 1},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 23
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.plantYellow.blockID},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
			}			
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.chest.blockID, 5},
				{0},
				{Block.chest.blockID, 5},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.blockClay.blockID},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.furnaceIdle.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorIron.blockID, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorIron.blockID, 9},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.blockcultivateIdle.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.chest.blockID, 4},
				{0},
				{Block.chest.blockID, 4},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
				{0},
				{0},
				{Fossil.ancientStonebrick.blockID},
				{Fossil.ancientStonebrick.blockID},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}}};
}