package mods.fossil.gens.structure.academy;

import mods.fossil.Fossil;
import net.minecraft.block.Block;

public class Academy2
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST = 4097, CUSTOM_DISPENSER = 4098, ITEM_FRAME = 4099, PAINTING = 4100,
			SPAWN_VILLAGER = 4101, CUSTOM_SKULL = 4102, CUSTOM_SIGNWALL = 4103, CUSTOM_SIGNPOST = 4104, RANDOM_HOLE = 4105;

	/** Start of specific chests; I'll use negative values so as not to conflict with item types and such */
	public static final int CUSTOM_CHEST_1 = -1;

	/** Custom signs */
	public static final int CUSTOM_SIGN_1 = 1;

	public static final int[][][][] blockArrayAcademy =
	{//This is where all the x, y, z values go (i, j, k). They are broke down by
		//layer. This is how the array works building from x to z and by layer y,
		//then they are finished by removing all the world.setBlock and 
		//x, y, z coordinates leaving something like this {Block.stone.blockID},
		{//y = 5
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{Block.blockClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{},
				{},
			},
			{//x = 12
				{},
				{},
				{},
				{},
				{Block.web.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 13
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 14
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 15
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 16
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 17
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 18
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockClay.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 19
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.web.blockID},
				{},
			},
			{//x = 20
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 21
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 22
				{},
				{},
				{},
				{},
				{Block.blockClay.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 23
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 6
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherrack.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 12
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.blockClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 13
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 14
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 15
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 16
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 17
				{},
				{},
				{},
				{},
				{Block.blockClay.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 18
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.blockClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 19
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 20
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 21
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 22
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 23
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 7
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.web.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherrack.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherrack.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.blockClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 12
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{},
				{},
			},
			{//x = 13
				{},
				{},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 14
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 15
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 16
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 17
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.web.blockID},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 18
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 19
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
			},
			{//x = 20
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.web.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 21
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 22
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 23
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 8
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{Block.web.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.web.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.web.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 12
				{},
				{},
				{},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 13
				{},
				{},
				{},
				{},
				{Block.stoneSingleSlab.blockID, 5},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
				{},
			},
			{//x = 14
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 15
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 16
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.web.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 17
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.blockClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.blockClay.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 18
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 19
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 20
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 21
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 22
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.web.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 23
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 9
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.web.blockID},
				{Block.web.blockID},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.netherrack.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.fence.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 12
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.fence.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 13
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
				{},
			},
			{//x = 14
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
			},
			{//x = 15
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 16
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneBrick.blockID, 2},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 17
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 18
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.blockClay.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 19
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{},
			},
			{//x = 20
				{},
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{},
				{},
				{},
				{Block.glowStone.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 21
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 2, 0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.RANDOM_HOLE_L2, 0, Block.thinGlass.blockID},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 22
				{},
				{},
				{},
				{},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{Block.web.blockID},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{0},
				{0},
				{0},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{AcademyUtil.BIOME_BLOCK, 0, 1, 1},
				{},
			},
			{//x = 23
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}}};
}		