package mods.fossil.gens.structure.shipwreck;

import net.minecraft.block.Block;

public class ShipWreck1
{

	public static final int[][][][] blockArrayShipWreck1 =
	{//This is where all the x, y, z values go (i, j, k). They are broke down by
		//layer. This is how the array works building from x to z and by layer y,
		//then they are finished by removing all the world.setBlock and 
		//x, y, z coordinates leaving something like this {Block.stone.blockID},
		{//y = 0
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 1
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 2
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 3
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{Block.doorWood.blockID, 1},
				{Block.pressurePlatePlanks.blockID},
				{Block.chest.blockID, 5},
				{Block.chest.blockID, 5},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{Block.furnaceIdle.blockID, 2},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{Block.pressurePlatePlanks.blockID},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{Block.furnaceIdle.blockID, 2},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{Block.chest.blockID, 4},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.bed.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 4
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{Block.signWall.blockID, 2},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{Block.doorWood.blockID, 9},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.doorWood.blockID, 8},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.furnaceIdle.blockID, 2},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{Block.furnaceIdle.blockID, 2},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.glass.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			}			
		},
		{//y = 5
			{//x = 0
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 1
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 2
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 3
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 4
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 5
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 6
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 7
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 8
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 9
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 10
				{},
				{},
				{},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{ShipWreckUtil.RANDOM_HOLE, 0, Block.planks.blockID},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
			},
			{//x = 11
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{},
				{}
			}}};
}